### ISSUE TITLE
Compatibility with  Twitter Bootstrap

### ISSUE THREAD

**Issue by TrurlMcByte** [Coren/redmine_advanced_roadmap_v2#57]
In roadmap page related issues names is invisible at all, if used Twitter Bootstrap (for example from https://bitbucket.org/dkuk/a_common_libs)
It's related to overload of tooltip class (field_issue in /app/views/versions/_info.html.erb)
Looks like over render_issue_tooltip in redmine/app/helpers/issues_helper.rb

Environment:
  Redmine version                3.0.4.stable
  Ruby version                   1.9.3-p392 (2013-02-22) [x86_64-linux]
  Rails version                  4.2.3
Advanced roadmap & milestones plugin 2.4.2
A common libraries 1.1.4

**Comment by allustin** [comment]
Same sitiutaion on another enviroment

Environment:
  Redmine version                3.1.0.devel
  Ruby version                   2.0.0-p645 (2015-04-13) [x64-mingw32]
  Rails version                  4.2.3
  Database adapter               PostgreSQL

Redmine plugins:
  a_common_libs                  1.1.4
  advanced_roadmap_v2            2.4.2

**Comment by carukc** [comment]
I'm seeing this too.  

Part of the problem seems to be that the bootstrap css sets the tooltip class to:
* opacity: 0
* position: absolute;

A temporary fix is to set the .tooltip class (under .list.related-issues), somewhere in your own css, to:
* opacity: 1
* position: relative; (or sticky)

as follows:

.list.related-issues .tooltip {
     opacity: 1.0;
     position: relative;
}

I've not fully tested so there may be side effects.

**Comment by carukc** [comment]
ok... one possible side affect seems to be that the tooltip boxes in the last version seem to sit in a transparent box (you can see the list through the tooltip box)

**Comment by Coren** [comment]
Maybe I can just change the class name in both css & source code. I'll see that in a few days

**Comment by carukc** [comment]
That would be better!

May I also suggest that, while you are in that part of the code, you add separate classes to the header and footer in the related issues lists.  That's the tr and th tags under thread in table class="list related-issues"

It would be nice to be able to style the header and footer separately .  On the template that I use the text in the total column is aligned with the title rather than the data in the columns.  This change would allow me to style them independently.

Thanks
Chris

**Comment by Coren** [comment]
Can you test and tell me if it's ok for you ?

**Comment by carukc** [comment]
Works for me.  I can see the class on the tr tag too.  Many Thanks!

Chris
